import json
import sqlite3
from pathlib import Path

def load_json(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)

def generate_postgres_sql(data_dir: Path, output_path: Path):
    surahs = load_json(data_dir / "surahs.json")
    ayahs = load_json(data_dir / "ayahs.json")
    words = load_json(data_dir / "words.json")
    juzs = load_json(data_dir / "juzs.json")
    hizbs = load_json(data_dir / "hizbs.json")
    rubs = load_json(data_dir / "rubs.json")
    pages = load_json(data_dir / "pages.json")
    editions = load_json(data_dir / "editions.json")

    with output_path.open("w", encoding="utf-8") as f:
        f.write("-- Quran Database Export (PostgreSQL)\n")
        f.write("-- Generated by Quran Developer Platform\n\n")

        # Tables
        f.write("CREATE TABLE surahs (\n  id SERIAL PRIMARY KEY,\n  number INTEGER UNIQUE NOT NULL,\n  name_ar TEXT NOT NULL,\n  name_en TEXT NOT NULL,\n  name_en_translation TEXT NOT NULL,\n  type TEXT NOT NULL\n);\n\n")
        
        f.write("CREATE TABLE juzs (\n  id INTEGER PRIMARY KEY,\n  ayah_count INTEGER,\n  start_ayah_number INTEGER,\n  end_ayah_number INTEGER,\n  start_page INTEGER,\n  end_page INTEGER,\n  surah_ids TEXT\n);\n\n")

        f.write("CREATE TABLE hizbs (\n  id INTEGER PRIMARY KEY,\n  ayah_count INTEGER,\n  start_ayah_number INTEGER,\n  end_ayah_number INTEGER,\n  start_page INTEGER,\n  end_page INTEGER,\n  surah_ids TEXT\n);\n\n")

        f.write("CREATE TABLE rubs (\n  id INTEGER PRIMARY KEY,\n  ayah_count INTEGER,\n  start_ayah_number INTEGER,\n  end_ayah_number INTEGER,\n  start_page INTEGER,\n  end_page INTEGER,\n  surah_ids TEXT\n);\n\n")

        f.write("CREATE TABLE pages (\n  id INTEGER PRIMARY KEY,\n  ayah_count INTEGER,\n  start_ayah_number INTEGER,\n  end_ayah_number INTEGER,\n  start_page INTEGER,\n  end_page INTEGER,\n  surah_ids TEXT\n);\n\n")

        f.write("CREATE TABLE ayahs (\n  id INTEGER PRIMARY KEY,\n  number INTEGER UNIQUE NOT NULL,\n  text TEXT NOT NULL,\n  number_in_surah INTEGER NOT NULL,\n  page INTEGER REFERENCES pages(id),\n  surah_id INTEGER REFERENCES surahs(id),\n  hizb_id INTEGER REFERENCES rubs(id), -- SQL hizb_id is rub_id\n  juz_id INTEGER REFERENCES juzs(id),\n  sajda BOOLEAN DEFAULT FALSE\n);\n\n")

        f.write("CREATE TABLE words (\n  id INTEGER PRIMARY KEY,\n  ayah_id INTEGER REFERENCES ayahs(id),\n  text TEXT NOT NULL,\n  position INTEGER NOT NULL,\n  surah_id INTEGER REFERENCES surahs(id),\n  number_in_surah INTEGER NOT NULL,\n  root TEXT,\n  morphology TEXT\n);\n\n")

        f.write("CREATE TABLE editions (\n  id SERIAL PRIMARY KEY,\n  identifier TEXT UNIQUE NOT NULL,\n  language TEXT NOT NULL,\n  name TEXT NOT NULL,\n  englishName TEXT NOT NULL,\n  format TEXT NOT NULL,\n  type TEXT NOT NULL\n);\n\n")

        # Data Insertion (Batched for Postgres efficiency)
        def write_inserts(table, data):
            if not data: return
            cols = ", ".join(data[0].keys())
            f.write(f"INSERT INTO {table} ({cols}) VALUES\n")
            for i, row in enumerate(data):
                vals = []
                for v in row.values():
                    if v is None: vals.append("NULL")
                    elif isinstance(v, bool): vals.append("TRUE" if v else "FALSE")
                    elif isinstance(v, str): vals.append("'" + v.replace("'", "''") + "'")
                    elif isinstance(v, list): vals.append("'" + json.dumps(v).replace("'", "''") + "'")
                    else: vals.append(str(v))
                
                suffix = "," if i < len(data) - 1 else ";"
                f.write(f"  ({', '.join(vals)}){suffix}\n")
            f.write("\n")

        write_inserts("surahs", surahs)
        write_inserts("juzs", juzs)
        write_inserts("hizbs", hizbs)
        write_inserts("rubs", rubs)
        write_inserts("pages", pages)
        write_inserts("ayahs", ayahs)
        write_inserts("editions", editions)
        
        # Words are many, split into batches
        batch_size = 5000
        for i in range(0, len(words), batch_size):
            write_inserts("words", words[i:i+batch_size])

        # Indexes
        f.write("CREATE INDEX idx_ayahs_surah ON ayahs(surah_id);\n")
        f.write("CREATE INDEX idx_ayahs_juz ON ayahs(juz_id);\n")
        f.write("CREATE INDEX idx_ayahs_page ON ayahs(page);\n")
        f.write("CREATE INDEX idx_words_ayah ON words(ayah_id);\n")
        f.write("CREATE INDEX idx_words_surah ON words(surah_id);\n")

    print(f"Generated PostgreSQL export at {output_path}")

def generate_sqlite(data_dir: Path, output_path: Path):
    surahs = load_json(data_dir / "surahs.json")
    ayahs = load_json(data_dir / "ayahs.json")
    words = load_json(data_dir / "words.json")
    juzs = load_json(data_dir / "juzs.json")
    hizbs = load_json(data_dir / "hizbs.json")
    rubs = load_json(data_dir / "rubs.json")
    pages = load_json(data_dir / "pages.json")
    editions = load_json(data_dir / "editions.json")

    if output_path.exists(): output_path.unlink()

    conn = sqlite3.connect(output_path)
    cur = conn.cursor()

    # Tables
    cur.execute("CREATE TABLE surahs (id INTEGER PRIMARY KEY, number INTEGER UNIQUE, name_ar TEXT, name_en TEXT, name_en_translation TEXT, type TEXT)")
    cur.execute("CREATE TABLE juzs (id INTEGER PRIMARY KEY, ayah_count INTEGER, start_ayah_number INTEGER, end_ayah_number INTEGER, start_page INTEGER, end_page INTEGER, surah_ids TEXT)")
    cur.execute("CREATE TABLE hizbs (id INTEGER PRIMARY KEY, ayah_count INTEGER, start_ayah_number INTEGER, end_ayah_number INTEGER, start_page INTEGER, end_page INTEGER, surah_ids TEXT)")
    cur.execute("CREATE TABLE rubs (id INTEGER PRIMARY KEY, ayah_count INTEGER, start_ayah_number INTEGER, end_ayah_number INTEGER, start_page INTEGER, end_page INTEGER, surah_ids TEXT)")
    cur.execute("CREATE TABLE pages (id INTEGER PRIMARY KEY, ayah_count INTEGER, start_ayah_number INTEGER, end_ayah_number INTEGER, start_page INTEGER, end_page INTEGER, surah_ids TEXT)")
    cur.execute("CREATE TABLE ayahs (id INTEGER PRIMARY KEY, number INTEGER UNIQUE, text TEXT, number_in_surah INTEGER, page INTEGER, surah_id INTEGER, hizb_id INTEGER, juz_id INTEGER, sajda BOOLEAN)")
    cur.execute("CREATE TABLE words (id INTEGER PRIMARY KEY, ayah_id INTEGER, text TEXT, position INTEGER, surah_id INTEGER, number_in_surah INTEGER, root TEXT, morphology TEXT)")
    cur.execute("CREATE TABLE editions (id INTEGER PRIMARY KEY, identifier TEXT UNIQUE, language TEXT, name TEXT, englishName TEXT, format TEXT, type TEXT)")

    def insert_batch(table, data):
        if not data: return
        cols = ", ".join(data[0].keys())
        placeholders = ", ".join(["?"] * len(data[0]))
        sql = f"INSERT INTO {table} ({cols}) VALUES ({placeholders})"
        
        rows = []
        for d in data:
            row = []
            for v in d.values():
                if isinstance(v, (list, dict)): row.append(json.dumps(v))
                else: row.append(v)
            rows.append(tuple(row))
        
        cur.executemany(sql, rows)

    insert_batch("surahs", surahs)
    insert_batch("juzs", juzs)
    insert_batch("hizbs", hizbs)
    insert_batch("rubs", rubs)
    insert_batch("pages", pages)
    insert_batch("ayahs", ayahs)
    insert_batch("editions", editions)
    
    batch_size = 5000
    for i in range(0, len(words), batch_size):
        insert_batch("words", words[i:i+batch_size])

    # Indexes
    cur.execute("CREATE INDEX idx_ayahs_surah ON ayahs(surah_id)")
    cur.execute("CREATE INDEX idx_ayahs_juz ON ayahs(juz_id)")
    cur.execute("CREATE INDEX idx_ayahs_page ON ayahs(page)")
    cur.execute("CREATE INDEX idx_words_ayah ON words(ayah_id)")
    cur.execute("CREATE INDEX idx_words_surah ON words(surah_id)")

    conn.commit()
    conn.close()
    print(f"Generated SQLite export at {output_path}")

if __name__ == "__main__":
    data_dir = Path("lib/data")
    generate_postgres_sql(data_dir, Path("public/quran_postgres.sql"))
    generate_sqlite(data_dir, Path("public/quran_indexed.sqlite"))
